### PR TITLE
Make unmarshaling json config strict

### LINKED ISSUE #274: Crash FLP on an incorrect config file
Currently, FLP will start normally even if its config has unknown fields.
The problem is that misspelled fields will silently be ignored and have default values.
It's better to crash FLP with an indicative error.

### PR DESCRIPTION
**Pull request by ronensc**
Unmarshaling non-config related json still use the non-strict version.

This is a follow-up on #271 
Fix #274

### CODE REVIEW

File: pkg/test/utils.go [hunk 1]
```diff
@@ -143,6 +143,7 @@ func RunCommand(command string) string {
 }
 
 func DeserializeJSONToMap(t *testing.T, in string) config.GenericMap {
+	t.Helper()
```
Comment (KalmanMeth) [inline pkg/test/utils.go:146]: What is the practical result of declaring this function as a Helper function?

**Review by KalmanMeth — APPROVED** [review]

File: pkg/test/utils.go (hunk 1 above)
Comment (ronensc) [reply pkg/test/utils.go:146]: @KalmanMeth 
By marking a function as helper, when a test fails in the helper function, the line number reported will be of the caller function rather than inside the test helper function.

Consider running the following test:

```golang
package b

import (
	"testing"
)

func Test(t *testing.T) {
	helperMarked(t, "hello", "hi") // line 8
	helperUnmarked(t, "hello", "hi")
}

func helperMarked(t *testing.T, expected, actual string) {
	t.Helper()
	if expected != actual {
		t.Errorf("expected (%v) != actual(%v)", expected, actual)
	}
}
func helperUnmarked(t *testing.T, expected, actual string) {
	if expected != actual {
		t.Errorf("expected (%v) != actual(%v)", expected, actual) // line 20
	}
}
```

The result is:
```
=== RUN   Test
    b_test.go:8: expected (hello) != actual(hi)
    b_test.go:20: expected (hello) != actual(hi)
--- FAIL: Test (0.00s)

FAIL
```

Comment (jotak) [reply pkg/test/utils.go:146]: nice, I didn't know that

**Review by jotak — APPROVED** [review]
lgtm
